- README.adoc
- external/pom.xml
- external/src/main/docker/Dockerfile.jvm
- external/src/main/docker/Dockerfile.native
- external/src/main/resources/application.properties
The ui-frontend already uses ports 8080 and 5005. Use 8083 and 5006 instead, so that one can run both locally at the same time.
> Small changes for ports to not clash with the UI-backend and debugger.

- .github/workflows/maven.yml
- api/src/main/java/org/hawkular/alerts/api/model/condition/EventCondition.java
- api/src/test/java/org/hawkular/alerts/api/EventConditionTest.java
- engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
- engine/src/main/java/org/hawkular/alerts/engine/impl/DroolsRulesEngineImpl.java
- engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl
- engine/src/test/resources/hawkular-alerts.properties
- external/pom.xml
- external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/EmailActionPluginListener.java
- external/src/main/java/com/redhat/cloud/custompolicies/engine/handlers/EventsHandler.java
- external/src/main/java/com/redhat/cloud/custompolicies/engine/handlers/ImportHandler.java
- external/src/test/groovy/org/hawkular/alerts/rest/AbstractQuarkusITestBase.groovy
- external/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy
- external/src/test/groovy/org/hawkular/alerts/rest/AlertsITest.groovy
- external/src/test/groovy/org/hawkular/alerts/rest/ConditionsITest.groovy
- external/src/test/groovy/org/hawkular/alerts/rest/DampeningITest.groovy
- external/src/test/groovy/org/hawkular/alerts/rest/EventsITest.groovy
- external/src/test/groovy/org/hawkular/alerts/rest/EventsLifecycleITest.groovy
- external/src/test/groovy/org/hawkular/alerts/rest/GroupITest.groovy
- external/src/test/groovy/org/hawkular/alerts/rest/ImportExportITest.groovy
- external/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy
- external/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy
- external/src/test/resources/application.properties
- external/src/test/resources/import/alerts-data.json
- external/src/test/resources/import/groups-data.json
- pom.xml
When -Pitest is added, runs integration tests which have been ported from the Hawkular-Alerts (with some modifications if the functionality has changed in the custom-policies-engine). Targets the REST-interface only at this point. Not all of the integration tests will be ported as some of those don't make sense anymore.
Also, adds -Pitest to the Github Actions, updates Quarkus to 1.1.0.Final and some smaller updates to maven files.
> CPOL-27 Run REST-interface integration tests

- commons/pom.xml
- commons/src/main/java/org/hawkular/alerts/log/AlertingLogger.java
- commons/src/main/java/org/hawkular/commons/log/MsgLogger.java
- engine/pom.xml
- engine/src/main/resources/META-INF/kmodule.xml
- external/pom.xml
- external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/QuarkusActionPluginRegister.java
- pom.xml
Remove all logging implementations from the project, leaving only the jboss-logging for the log message generation.
> CPOL-29 Let Quarkus configure the logging implementation

- external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/BetaHooksActionPluginRegister.java
- external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/EmailActionPluginListener.java
- external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/WebhookActionPluginListener.java
- external/src/main/java/com/redhat/cloud/custompolicies/engine/process/Receiver.java
```
snert:custom-policies-engine hrupp$ curl localhost:8084/metrics/application
application_messages_outgoing_hook_count_total 0.0
application_messages_outgoing_email_count_total 0.0
application_messages_incoming_host_egress_count_total 176.0
application_messages_outgoing_webhook_count_total 0.0
```
> Add counters for incoming/outgoing messages.

- engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImpl.java
- engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImplTest.java
- external/src/main/java/com/redhat/cloud/custompolicies/engine/handlers/TriggersHandler.java
- external/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy
Return updated value after PUT and accept managed plugin updates without actionId (if previously one has been created with POST). 
If actionId is incorrect (missing or not found), reject with code 400.
> CPOL-131 FullTriggerUpdate changes

- external/src/main/java/com/redhat/cloud/policies/engine/AlertStarter.java
When running in images built by s2i for Openshift, prints the commit sha in the logs when starting.
> POL-237 Add commit SHA in the starting logs

- api/src/main/java/org/hawkular/alerts/api/model/event/Event.java
- engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java
- engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImplTest.java
- engine/src/test/resources/META-INF/microprofile-config.properties
- external/src/main/resources/application.properties
- external/src/test/resources/application.properties
Also, when saving an event or alert, do not store the trigger's lifecycle history with it.
> POL-286 Add the ability to store only thin alerts

- external/src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
- external/src/main/resources/application.properties
This data id is encoded in stored triggers and provided by the ui-backend when triggers are created.
Changing that value would require data migration in the engine's backend store.
> POL-307 Rename Data id back, as triggers expect the old value.

- external/src/main/java/com/redhat/cloud/policies/engine/actions/plugins/NotificationActionPluginListener.java
- external/src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
- external/src/test/java/com/redhat/cloud/policies/engine/process/ReceiverTest.java
Haven't tested with real data. I'm using `updated` because that's the value that appearas to be used in inventory as "Last Check-in". That value (updated) also appears in inventory API: `https://cloud.redhat.com/api/inventory/v1/hosts/{the-id}`
> POL-341 Use "updated" as the timestamp for the notification

- external/src/main/java/com/redhat/cloud/policies/engine/metrics/HeartbeatHandler.java
This then prints a message to the log like the following once an hour (manually added a bogus message via kafkacat).
It basically shows the receiver stats for now. We can add more (like number of messages forwarded to notifications).
It is not meant to replace metrics via Prometheus/Grafana and alerting on them, but rather to show a sign of life in the logs.
`2021-01-25 11:22:19,005 INFO  [HeartbeatHandler] (executor-thread-1) Heartbeat: processed 1, rejected 0, process errors 1
`
> Add a scheduled handler to print a heartbeat message.

- external/src/main/java/com/redhat/cloud/policies/engine/handlers/AdminHandler.java
- external/src/main/java/com/redhat/cloud/policies/engine/handlers/LivenessHandler.java
This requires a put-request to /admin/down. There is currently no other protection other than the assumption that this is behind a secured gateway.
> Add a way to set the engine's liveness to admin-down.

- external/src/main/java/com/redhat/cloud/policies/engine/actions/plugins/NotificationActionPluginListener.java
- external/src/main/java/com/redhat/cloud/policies/engine/actions/plugins/notification/PoliciesAction.java
- external/src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
- external/src/test/java/com/redhat/cloud/policies/engine/process/ReceiverFilterTest.java
- external/src/test/java/com/redhat/cloud/policies/engine/process/ReceiverTest.java
-  insights_id: An ID defined in /etc/insights-client/machine-id. This field is considered a canonical fact.
-  id: A durable and reliable platform-wide host identifier. Applications  should use this identifier to reference hosts.
> Remove insights_id and add inventory_id (id)

- engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java
- external/src/main/java/com/redhat/cloud/policies/engine/AlertStarter.java
⚠️ Temp PR, will be reverted after we're done fixing the issue.
This PR will print all environment variables keys at application startup.
Values will also be printed but only if they start with a String that matches one of the elements of `PREFIX_WHITELIST`.
> Print whitelisted env vars and conf values at application startup

- api/pom.xml
- api/src/main/java/org/hawkular/alerts/api/services/AlertsService.java
- engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
- engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java
- engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnBaseServiceImplTest.java
- external/src/main/java/com/redhat/cloud/policies/engine/handlers/EventsHandler.java
- external/src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
- external/src/test/java/com/redhat/cloud/policies/engine/process/MockedAlertsService.java
- external/src/test/java/com/redhat/cloud/policies/engine/process/ReceiverFilterTest.java
This may fix the `VertxException` we have on prod.
Even if it does not fix the exception, it is still an improvement: Kafka messages are now processed in a non-blocking way.
> POL-532 Process Kafka messages in a non-blocking way

- external/src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
This will hopefully fix the `io.vertx.core.VertxException: Thread blocked` we have on prod.
> Process events from a worker thread

- api/src/main/java/org/hawkular/alerts/api/model/Lifecycle.java
- api/src/main/java/org/hawkular/alerts/api/model/trigger/Trigger.java
- engine/src/main/java/org/hawkular/alerts/engine/cache/ActionsCacheManager.java
- engine/src/main/java/org/hawkular/alerts/engine/cache/PublishCacheManager.java
- engine/src/main/java/org/hawkular/alerts/engine/impl/PartitionManagerImpl.java
- engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnActionsServiceImpl.java
- engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java
- engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImpl.java
- engine/src/main/java/org/hawkular/alerts/filter/CacheClient.java
I use JFR / MissionControl for my `policies-history` work to check the impact of code changes on the prod memory leak (which is really easy to reproduce locally BTW). Heap old gen analysis showed a lot of `ArrayList`/`HashSet` resizes and also cache `read` operations after `put` operations while we don't use the returned values. This PR contains short-term optimizations that will lower the number of objects stored in the old gen. It only mitigates some of the consequences of the leak but does not fix the cause at all. Don't expect a fantastic result, but there will be a slight improvement.
See [this article](https://infinispan.org/blog/2012/09/04/speeding-up-cache-calls-with) about the reason why we should use `Flag.IGNORE_RETURN_VALUES`.
> Lower the number of objects stored in the heap old gen

- external/src/main/java/com/redhat/cloud/policies/engine/history/PoliciesHistory.java
- external/src/main/resources/application.properties
This will start persisting the policies-history entries into Postgres on prod.
At least 14 days later, we will enable policies-history in policies-ui-backend. Until then, the ui-backend will still consume the history data from Infinispan.
I am changing this boolean rather than the one in app-interface to keep dev and prod in a synced state. The boolean in app-interface is still there to disable policies-history in case of emergency.
> POL-450 Enable policies-history by default

- .github/workflows/maven.yml
- external/src/main/docker/Dockerfile-build.jvm
Build logs will be much shorter with this in Jenkins and GH.
> Hide Maven downloads progress in build logs

- engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
- external/src/main/java/org/hawkular/alerts/AlertsStandalone.java
- external/src/main/resources/application.properties
- external/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy
This PR disables the triggers lifecycle which means that when a trigger is fired, it will no longer:
- be loaded from Infinispan
- have its lifecycle updated
- be saved into Infinispan
ℹ️ This is tested with IQE tests on ephemeral and they all passed.
> POL-561 Stop persisting triggers history in Infinispan

- external/src/main/resources/application.properties
This should help reducing the amount of data stored in Infinispan.
AFAIU, alerts are processed by the engine almost immediately and transformed into actions sent as Kafka payloads on the `ingress` topic. After that, I don't see why we would need to keep the alerts in the cache.
This change will be fully effective 7 days after the redeployment because the old alerts will still be stored for 7 days.
> Lower the alerts lifespan to 24 hours

- engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnActionsServiceImpl.java
- external/src/main/resources/application.properties
- external/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy
This PR may or may not have a significant impact on the stage/prod memory leak. 😄 
I am able to reproduce a memory leak on my machine using JMeter and a large number of incoming Kafka messages on the `platform.inventory.events` topic. As a consequence, I had the occasion to analyze a few heap dumps and to test many code changes.
Here's what I suspect. With the current `master` code, the garbage collector is unable to release the memory allocated to an `Alert` because of the `Action#event` field which holds a reference to the `Alert`. The `Action` is stored in a volatile Infinispan cache for a duration corresponding to the `Alert` lifespan configured in `application.properties` (currently 24h). After that delay, the `Alert` becomes eligible to garbage collection.
I don't think we need to …
> Disable actions store

- external/src/main/java/com/redhat/cloud/policies/engine/clowder/KafkaSaslInitializer.java
The truststore type should by PEM but Kafka tries to load a JKS keystore instead... Let's check if the config is correct.
> POL-621 Log Kafka config values

- external/src/main/java/com/redhat/cloud/policies/engine/clowder/KafkaSaslInitializer.java
`clowder-quarkus-config-source` has been updated, the hardcoded env var should no longer be needed.
> POL-621 Remove hardcoded Kafka SASL env var

- .rhcicd/clowdapp.yaml
This PR makes [this config value](https://github.com/RedHatInsights/policies-engine/blob/89ebb1fa7b5a8056aeb1546a957f4e7dbb8d156f/external/src/main/resources/application.properties#L98) configurable from env vars. IIUC, it is used in [AlertsEngineImpl](https://github.com/RedHatInsights/policies-engine/blob/89ebb1fa7b5a8056aeb1546a957f4e7dbb8d156f/engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java#L126) to determine the period between two executions of [RulesInvoker](https://github.com/RedHatInsights/policies-engine/blob/89ebb1fa7b5a8056aeb1546a957f4e7dbb8d156f/engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java#L595) which is where the events are processed and transformed into notifications.
Increasing the period _may_ help alleviate (or even …
> Make engine.alerts.engine-period configurable from app-interface

- external/src/main/java/com/redhat/cloud/policies/engine/handlers/TriggersHandler.java
This will show us how many times each `policies-engine` REST endpoint from `TriggersHandler` is called and by who.
> Add temp counters to investigate an engine instability

- .rhcicd/clowdapp.yaml
- api/src/main/java/org/hawkular/alerts/api/services/LightweightEngine.java
- engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
- external/src/main/java/com/redhat/cloud/policies/engine/LightweightEngineImpl.java
- external/src/main/java/com/redhat/cloud/policies/engine/actions/plugins/NotificationActionPluginListener.java
- external/src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
- external/src/main/java/org/hawkular/alerts/AlertsStandalone.java
- external/src/main/resources/application.properties
- external/src/test/java/com/redhat/cloud/policies/engine/process/ReceiverTest.java
This PR is the first step of the removal of Infinispan, Drools and most of Hawkular from `policies-engine`. This step is only focused on making the Kafka messages processing simpler.
:information_source: If the `lightweight-engine.enabled` config key is set to `false` (which will be the default value), this PR does not have any impact on prod and can be merged safely.
Now, let's talk about what's changed :smiley: 
:arrow_forward: **BEFORE**
:arrow_forward: **AFTER**
:arrow_forward: **Important details**
- All triggers are loaded in memory (in a `HashMap`). This should be equivalent to what we had before since the triggers were loaded in memory through Drools. However, we will have to monitor the heap for a while to make sure everything's fine.
- The old logic based on a `TimerTask` …
> POL-649 Introduce LightweightEngine

- external/src/main/java/com/redhat/cloud/policies/engine/LightweightEngineImpl.java
Surprisingly, existing triggers are `reloaded` instead of `loaded` when the engine starts on stage.
> POL-649 Load trigger on reloading failure

- external/src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
- external/src/test/java/com/redhat/cloud/policies/engine/process/ReceiverFilterTest.java
Kafka messages can't be processed on the event loop thread when `LightweightEngine` is enabled because that thread does not support JTA transactions:
```
2022-05-03 20:28:09,297 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-0) SRMSG00201: Error caught while processing a message: io.quarkus.runtime.BlockingOperationNotAllowedException: Cannot start a JTA transaction from the IO thread.
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:30)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeIn …
```
> POL-649 Process Kafka messages on worker thread

- external/src/main/java/com/redhat/cloud/policies/engine/LightweightEngineImpl.java
Fixes
```
2022-05-04 07:14:24,807 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-0) SRMSG00201: Error caught while processing a message: java.util.ConcurrentModificationException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511)
at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1539)
at com.redhat.cloud.policies.engine.LightweightEngineImpl.fireTriggers(LightweightEngineImpl.java:230)
at com.redhat.cloud.policies.engine.LightweightEngineImpl.process(LightweightEngineImpl.java:131)
at com.redhat.cloud.policies.engine.LightweightEngineImpl_ClientProxy.process(Unknown Source)
at com.redhat.cloud.policies.engine.process.Receiver.processAsync(Receiver.java:197)
at com.redhat.cloud.policies.engine.process.Receiver_ClientProxy.processAsync(Unknown …
```
> POL-649 Support concurrency in LightweightEngineImpl triggers map

- engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java
#373 fixed a bug but also added a duplicate `LightweightEngine#removeTrigger` call when a trigger is deleted. This PR removes the duplicate.
> POL-649 Remove duplicate LightweightEngine call

- api/src/main/java/org/hawkular/alerts/api/services/LightweightEngine.java
- external/src/main/java/com/redhat/cloud/policies/engine/lightweight/LightweightEngineImpl.java
- external/src/main/java/com/redhat/cloud/policies/engine/lightweight/LightweightEngineResource.java
Related to https://github.com/RedHatInsights/policies-ui-backend/pull/426.
When an invalid condition is validated on stage with the lightweight engine, the validation error message isn't forwarded to the browser. This is the first half of the fix.
> POL-649 Return condition validation error in REST response

- external/src/main/java/com/redhat/cloud/policies/engine/db/StatelessSessionFactory.java
- external/src/main/java/com/redhat/cloud/policies/engine/history/PoliciesHistory.java
- external/src/main/java/com/redhat/cloud/policies/engine/lightweight/TriggersLoader.java
- external/src/test/java/com/redhat/cloud/policies/engine/db/StatelessSessionFactoryTest.java
The Hibernate stateful session has an internal L1 cache which isn't cleared between two Kafka messages processing and can lead to using outdated DB data. We already fixed that in `notifications-backend` with `StatelessSessionFactory`. This PR introduces the same changes in `policies-engine`.
> POL-649 Introduce StatelessSessionFactory

- external/pom.xml
That dependency was previously declared in the pom.xml from the `engine` module which has been completely removed from the project.
> POL-649 Add clowder-quarkus-config-source in external module

- .rhcicd/clowdapp.yaml
This PR:
- removes all ClowdApp configuration related to the persistent volume
- slightly reduces the probes initial delay
- lowers the CPU/memory requests and limits
⚠️ It may cause the removal of the PV and all its data at deployment time. I am not sure whether that will happen automatically or if a human action (from devprod) will be needed to delete it.
> POL-649 Remove PV claim and lower resources limits

- .rhcicd/clowdapp.yaml
Fixes
```
Error creating: pods "policies-engine-service-5998fd7cff-w8rsw" is forbidden: memory max limit to request ratio per Container is 2, but provided ratio is 2.048000
```
> POL-649 Fix memory limit to request ratio

- .rhcicd/clowdapp.yaml
Now that Infinispan is gone, we probably no longer need to override the `GC_MAX_METASPACE_SIZE` and `JAVA_CORE_LIMIT` default values from the JVM.
WDYT @pilhuhn?
> Stop overriding JVM default settings

- .rhcicd/clowdapp.yaml
Metrics show that the current CPU request and limit are way above the actual CPU used by the containers on prod.
> Decrease default CPU request/limit

- src/main/java/com/redhat/cloud/policies/engine/RunOnStartup.java
- src/main/java/com/redhat/cloud/policies/engine/clowder/KafkaSaslInitializer.java
- src/main/java/com/redhat/cloud/policies/engine/condition/ConditionParser.java
- src/main/java/com/redhat/cloud/policies/engine/db/StatelessSessionFactory.java
- src/main/java/com/redhat/cloud/policies/engine/db/repositories/PoliciesHistoryRepository.java
- src/main/java/com/redhat/cloud/policies/engine/db/repositories/PoliciesRepository.java
- src/main/java/com/redhat/cloud/policies/engine/metrics/ProcSelfStatusExporter.java
- src/main/java/com/redhat/cloud/policies/engine/process/EventProcessor.java
- src/main/java/com/redhat/cloud/policies/engine/process/NotificationSender.java
- src/main/java/com/redhat/cloud/policies/engine/process/PayloadParser.java
- src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
- src/main/java/com/redhat/cloud/policies/engine/rest/LightweightEngineResource.java
Quarkus recently introduced a new `Log` API which delegates all its invocations to `org.jboss.logging.Logger`. Building the logger is no longer needed.
> Use the new Quarkus Log API

- src/main/java/com/redhat/cloud/policies/engine/db/entities/PoliciesHistoryEntry.java
- src/main/java/com/redhat/cloud/policies/engine/process/EventProcessor.java
I am monitoring `stage` with the `orgId` enabled. This will make some log entries clearer.
> Improve log messages related to orgId

- src/main/java/com/redhat/cloud/policies/engine/condition/ConditionParser.java
This is an emergency fix for production.
Pods are crashlooping because of the following exception:
```
2023-02-14 10:44:47,076 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-0) SRMSG00201: Error caught while processing a message in method com.redhat.cloud.policies.engine.process.Receiver#process: java.lang.NullPointerException
at java.base/java.lang.String.contains(String.java:2036)
at com.redhat.cloud.policies.engine.condition.ConditionParser$ExprVisitor.visitExpr(ConditionParser.java:262)
at com.redhat.cloud.policies.engine.condition.ConditionParser$ExprVisitor.visitObject(ConditionParser.java:108)
at com.redhat.cloud.policies.engine.condition.ConditionParser$ExprVisitor.visitExpression(ConditionParser.java:97)
at com.redhat.cloud.policies.engine.condition.ConditionParser$ExprV …
```
> Prevent NPE in ConditionParser

- helpers/kafka-sasl-ssl/.env
- helpers/kafka-sasl-ssl/.gitignore
- helpers/kafka-sasl-ssl/README.adoc
- helpers/kafka-sasl-ssl/cdappconfig-template.json
- helpers/kafka-sasl-ssl/create-certs.sh
- helpers/kafka-sasl-ssl/docker-compose.yml
- helpers/kafka-sasl-ssl/kafka_server_jaas.conf
- helpers/kafka-ssl/.env
- helpers/kafka-ssl/README.adoc
- helpers/kafka-ssl/create-certs.sh
- helpers/kafka-ssl/docker-compose.yml
- Do not recrease
- Include creationg in docker-compose startup
Some improvements to help testing kafka ssl
Easier to review with [hide whitespaces on](https://github.com/RedHatInsights/policies-engine/pull/497/files?diff=unified&w=1)
> Create certs using kafka's java version

- src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
The Policies engine isn't protected enough against [Kafka poison pills](https://medium.com/lydtech-consulting/kafka-poison-pill-e146b87c1866). This PR adds the most basic yet very efficient way of preventing that kind of issue. You may want to use a different [error handling strategy](https://quarkus.io/guides/kafka#error-handling) in the future but in the meantime I recommend that this PR is merged as a first step.
> RHCLOUD-24299 Protect against Kafka poison pills

- pom.xml
- src/main/java/com/redhat/cloud/policies/engine/db/entities/PoliciesHistoryEntry.java
- src/main/java/com/redhat/cloud/policies/engine/db/repositories/PoliciesHistoryRepository.java
- src/main/java/com/redhat/cloud/policies/engine/process/Event.java
- src/main/java/com/redhat/cloud/policies/engine/process/PayloadParser.java
- src/test/java/com/redhat/cloud/policies/engine/db/repositories/PoliciesHistoryRepositoryTest.java
- src/test/java/com/redhat/cloud/policies/engine/process/EventTest.java
- src/test/java/com/redhat/cloud/policies/engine/process/PayloadParserTest.java
- src/test/resources/db/migration/V25__RHINENG-1161_add_host_groups.sql
- src/test/resources/input/host.json
Host groups are taken from inventory updates Kafka messages and stored on `PoliciesHistoryEntry` on a JSONB field `host_groups`.
`io.quarkiverse.hibernatetypes` is utilized to add support for JSONB fields, a they are being introduced from Hibernate version 6.2 (Quarkus 3 and up). However, our Quarkus version 2 uses Hibernate version 5.
Needs to be done together with https://github.com/RedHatInsights/policies-ui-backend/pull/559
RHINENG-1161
> feat: collect host groups for history entries

- .rhcicd/build_deploy.sh
This PR updates the `Security-Compliance Tag` Naming Convention within the `build_deploy.sh` to make it easier to identify the Git Commit the image is based on.
Example:
- OLD: `sc-20230920`
- NEW: `sc-20230920-f963f6f`
> Update Security-Compliance Tag Naming Convention

- .rhcicd/build_deploy.sh
This PR is pushing updates to the `build_deploy.sh` from the `security-compliance` branch that supports proper Image tagging when an image is built using the `security-compliance` branch.
> Pushing support for the Security-Compliance Image Build to `main/master`

- pom.xml
- src/test/java/com/redhat/cloud/policies/engine/NonApplicationRootPathTest.java
Upgrades to newest Quarkus 2: 2.16.12.
Refactors tests to support this upgrade.
[RHINENG-2697](https://issues.redhat.com/browse/RHINENG-2697)
> chore: update quarkus 2.16.12

- .rhcicd/pr_check.sh
- pom.xml
- src/main/java/com/redhat/cloud/policies/engine/RunOnStartup.java
- src/main/java/com/redhat/cloud/policies/engine/clowder/KafkaSaslInitializer.java
- src/main/java/com/redhat/cloud/policies/engine/config/FeatureFlipper.java
- src/main/java/com/redhat/cloud/policies/engine/db/StatelessSessionFactory.java
- src/main/java/com/redhat/cloud/policies/engine/db/entities/OrgIdLatestUpdate.java
- src/main/java/com/redhat/cloud/policies/engine/db/entities/PoliciesHistoryEntry.java
- src/main/java/com/redhat/cloud/policies/engine/db/entities/Policy.java
- src/main/java/com/redhat/cloud/policies/engine/db/repositories/PoliciesHistoryRepository.java
- src/main/java/com/redhat/cloud/policies/engine/db/repositories/PoliciesRepository.java
- src/main/java/com/redhat/cloud/policies/engine/metrics/ProcSelfStatusExporter.java
- src/main/java/com/redhat/cloud/policies/engine/process/EventProcessor.java
- src/main/java/com/redhat/cloud/policies/engine/process/NotificationSender.java
- src/main/java/com/redhat/cloud/policies/engine/process/PayloadParser.java
- src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
- src/main/java/com/redhat/cloud/policies/engine/rest/LightweightEngineResource.java
- src/test/java/com/redhat/cloud/policies/engine/TestLifecycleManager.java
- src/test/java/com/redhat/cloud/policies/engine/db/StatelessSessionFactoryTest.java
- src/test/java/com/redhat/cloud/policies/engine/db/repositories/PoliciesHistoryRepositoryTest.java
- src/test/java/com/redhat/cloud/policies/engine/db/repositories/PoliciesRepositoryTest.java
- src/test/java/com/redhat/cloud/policies/engine/process/EventProcessorTest.java
- src/test/java/com/redhat/cloud/policies/engine/process/NotificationSenderTest.java
- src/test/java/com/redhat/cloud/policies/engine/process/PayloadParserTest.java
- src/test/java/com/redhat/cloud/policies/engine/process/ReceiverTest.java
Upgrades to Red Hat build of Quarkus 3.2.
Due to the migration, these fixes had to be applied:
* migration to Hibernate 6 type system, while keeping quarkus-hibernate-types
RHINENG-1631
RHINENG-774
> chore(upgrade): Quarkus 3.2

- .rhcicd/pr_check.sh
Updates the temporary policies-ui-backend reference within PR check, as the previous image was already removed (was from a PR).
> ci: update temporary backend-ui ref

- src/main/java/com/redhat/cloud/policies/engine/process/Event.java
- src/main/java/com/redhat/cloud/policies/engine/process/EventProcessor.java
- src/main/java/com/redhat/cloud/policies/engine/process/PayloadParser.java
- src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
- src/test/java/com/redhat/cloud/policies/engine/db/repositories/PoliciesHistoryRepositoryTest.java
- src/test/java/com/redhat/cloud/policies/engine/process/EventProcessorTest.java
- src/test/java/com/redhat/cloud/policies/engine/process/EventTest.java
- src/test/java/com/redhat/cloud/policies/engine/process/PayloadParserTest.java
- src/test/java/com/redhat/cloud/policies/engine/process/ReceiverTest.java
Improves processing logging by adding more debug logs, more information, and info logs for fired policies.
Besides that, it:
* re-throws JSON parse errors that later are captured and error logged 
* `Event` keeps recordKey (key from a Kafka message) -- for Inventory events this would be a host id
* `Event.id` is pre-generated as `UUID` and shared when producing a CloudEvent
* couple of code refactor to accommodate that
RHINENG-7089
> feat(consumer): improved processing logging

- .github/workflows/checkupdate.yml
Use jq to query for image digest to remove the need to rely on skopeo inspect output having json keys in particular order. RHINENG-13679
> fix(CI): use jq in checkimage

- .rhcicd/clowdapp.yaml
- src/main/docker/Dockerfile-build.jvm
> feat: expose JAVA_OPTIONS in deployments

- .rhcicd/clowdapp.yaml
After the Kafka OOM is fixed, getting back to the previou-ish values.
RHINENG-15124
> chore(cleanup): reduce heap on deployment
