.gitignore, src/main/java/com/redhat/cloud/custompolicies/engine/PolicyParser.java, src/main/java/com/redhat/cloud/custompolicies/engine/RestApi.java, src/test/java/com/redhat/cloud/custompolicies/engine/PolicyEvalTest.java, src/test/java/com/redhat/cloud/custompolicies/engine/PolicyParserTest.java, src/test/java/com/redhat/cloud/custompolicies/engine/PolicyVerificationTest.java, src/test/resources/system_profile_sample.json, src/test/sql/dbinit.sql
=> Test using a submitted system profile

engine/src/test/java/org/hawkular/alerts/engine/impl/DistributionTest.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/AlertStarter.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/handlers/EventsHandler.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/process/Receiver.java, external/src/test/java/com/redhat/cloud/custompolicies/engine/process/TypedJsonExtract.java, external/src/test/resources/input/host.json
Parse network_interfaces and yum_repos from the host json to more easily queryable format.
Also fix some import/logging stuff.
=> Improve insight-host-json's systemProfile parsing

api/pom.xml, api/src/main/java/com/redhat/cloud/custompolicies/api/model/condition/expression/ExprParser.java, api/src/main/java/org/hawkular/alerts/api/json/JsonUtil.java, api/src/test/java/com/redhat/cloud/custompolicies/api/model/condition/expression/ExprComplexTypeTest.java, api/src/test/java/org/hawkular/alerts/api/EventConditionMsgTest.java, engine/pom.xml, engine/src/test/java/org/hawkular/alerts/engine/RulesEngineTest.java, engine/src/test/resources/application.properties, external/src/main/java/com/redhat/cloud/custompolicies/engine/handlers/TriggersHandler.java
* Parses the error message from event condition (or any other condition validation)
* Modifies tests to use Quarkus JUnit5 and the JUnit5 legacy wrapper
* Remove all Jackson dependencies from poms instead use the Quarkus' provided version
=> CPOL-46 Parse correct error msg for event condition

api/src/main/java/org/hawkular/alerts/api/json/JsonUtil.java, external/pom.xml, external/src/main/java/com/redhat/cloud/custompolicies/engine/handlers/TriggersHandler.java, external/src/test/groovy/org/hawkular/alerts/rest/AbstractQuarkusITestBase.groovy, external/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy, external/src/test/groovy/org/hawkular/alerts/rest/AlertsITest.groovy, external/src/test/groovy/org/hawkular/alerts/rest/ConditionsITest.groovy, external/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy, pom.xml
Also remove RESTeasy dependency, change some logging levels.
=> CPOL-46 Add integration test for error message parsing

external/pom.xml, external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/QuarkusActionPluginRegister.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/process/Receiver.java, external/src/test/java/com/redhat/cloud/custompolicies/engine/ReceiverTest.java, external/src/test/resources/input/host.json
Although REST-tests are using Groovy, this is an example for another way of writing integration tests in the external component. This test checks the asynchronous messaging path.
=> Add Java integration test for the smallrye-messaging paths

external/src/main/resources/application.properties
A global bootstrap should be enough. We don't need them per topic.
=> Only use a global bootstrap server

external/pom.xml
Very simple addition so that we can start adding "engine" metrics configuration for Prometheus/Grafana
=> [CPOL-70] Added metrics endpoint

api/src/main/java/org/hawkular/alerts/actions/api/ActionPluginListener.java, api/src/main/java/org/hawkular/alerts/actions/api/Plugin.java, api/src/main/java/org/hawkular/alerts/api/services/ActionListener.java, api/src/main/java/org/hawkular/alerts/api/services/ActionsService.java, engine/src/main/java/org/hawkular/alerts/engine/impl/AlertsEngineImpl.java, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnActionsServiceImpl.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/QuarkusActionPluginListener.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/EmailActionPluginListener.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/WebhookActionPluginListener.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/process/Receiver.java, external/src/test/java/com/redhat/cloud/custompolicies/engine/ReceiverTest.java
ActionListeners are as such notified when the firing cycle has ended and all the queued events have been processed.
This one adds aggregation for insight_id to the EmailActionPluginListener to group by insight report's id.
=> CPOL-64 Add the flush method for actions 

api/src/main/java/org/hawkular/alerts/api/model/action/ActionDefinition.java, api/src/main/java/org/hawkular/alerts/api/model/trigger/TriggerAction.java, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImpl.java, engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImplTest.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/EmailActionPluginListener.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/WebhookActionPluginListener.java, external/src/main/resources/META-INF/resources/api/custom-policies/v1.0/openapi.json, external/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy, external/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy, external/src/test/java/com/redhat/cloud/custompolicies/engine/ReceiverTest.java, external/src/test/resources/import/alerts-data.json, external/src/test/resources/import/groups-data.json
Add the ability for plugins to manage their own properties (externally from engine) and autogenerate such action definitions from full triggers
=> CPOL-88 Managed mode for external plugin configuration, fulltrigger to create actionId

external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/BetaHooksActionPluginRegister.java, external/src/main/resources/application.properties, external/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy, external/src/test/resources/application.properties
Send every event, managed as managed plugin.
=> CPOL-86 CPOL-80 Integrate to beta hooks

external/src/main/java/com/redhat/cloud/custompolicies/engine/process/Receiver.java, external/src/main/resources/application.properties
=> Allow the receive to log a short message if an event is received.

external/src/main/java/com/redhat/cloud/custompolicies/engine/process/Receiver.java, external/src/main/resources/application.properties
Reverts RedHatInsights/custom-policies-engine#36
=> Revert "Allow the receive to log a short message if an event is received."

external/src/main/resources/application.properties
Default is String, could probably be done with UUID deserializer
=> Quick test in CI

external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/BetaHooksActionPluginRegister.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/EmailActionPluginListener.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/WebhookActionPluginListener.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/process/Receiver.java, external/src/main/resources/application.properties, external/src/test/java/com/redhat/cloud/custompolicies/engine/ReceiverTest.java
Change kafka-hosts to host-egress in the naming, test that receiver handles errors correctly and add metrics for those situations
=> Make changes to Receiver error handling

external/pom.xml, external/src/main/java/com/redhat/cloud/custompolicies/engine/actions/plugins/WebhookActionPluginListener.java, external/src/main/java/com/redhat/cloud/custompolicies/engine/process/Receiver.java, external/src/test/java/com/redhat/cloud/custompolicies/engine/ReceiverTest.java, external/src/test/java/com/redhat/cloud/custompolicies/engine/actions/plugins/EmailAggregateTest.java, external/src/test/resources/input/host.json
Also add tests to verify that the emails are properly aggregated by insights_id
=> CPOL-137 Return the insights_id to event's context

api/src/main/java/org/hawkular/alerts/api/model/condition/AvailabilityConditionEval.java, api/src/main/java/org/hawkular/alerts/api/model/condition/CompareConditionEval.java, api/src/main/java/org/hawkular/alerts/api/model/condition/Condition.java, api/src/main/java/org/hawkular/alerts/api/model/condition/ConditionEval.java, api/src/main/java/org/hawkular/alerts/api/model/condition/EventConditionEval.java, api/src/main/java/org/hawkular/alerts/api/model/condition/ExternalConditionEval.java, api/src/main/java/org/hawkular/alerts/api/model/condition/MissingConditionEval.java, api/src/main/java/org/hawkular/alerts/api/model/condition/NelsonConditionEval.java, api/src/main/java/org/hawkular/alerts/api/model/condition/RateConditionEval.java, api/src/main/java/org/hawkular/alerts/api/model/condition/StringConditionEval.java, api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdConditionEval.java, api/src/main/java/org/hawkular/alerts/api/model/condition/ThresholdRangeConditionEval.java, api/src/test/java/org/hawkular/alerts/api/JsonTest.java, engine/src/main/resources/org/hawkular/alerts/engine/rules/ConditionMatch.drl, external/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy, external/src/test/groovy/org/hawkular/alerts/rest/LifecycleITest.groovy
Fetching a trigger will now return the last eval set's timestamp (in json lastEvaluationTime)
=> CPOL-97 Add last evaluation time to trigger

external/src/main/java/com/redhat/cloud/policies/engine/actions/plugins/EmailActionPluginListener.java
See RedHatInsights/policies-notifications#5
Some Java for @theute
=> POL-149 Add insightId to the JSON message sent to notifications 

commons/src/main/resources/ispn-alerting-local.xml, engine/pom.xml, engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java, engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnActionsServiceImplTest.java, engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImplTest.java, engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImplTest.java, engine/src/test/resources/META-INF/microprofile-config.properties, engine/src/test/resources/application.properties, external/pom.xml, external/src/main/java/org/hawkular/alerts/AlertsStandalone.java, external/src/main/resources/application.properties, external/src/test/resources/application.properties
Migrate the data storage to using RocksDB
=> CPOL-141 Remove the need for reindexing everything at start. Use RocksDB

external/src/main/java/com/redhat/cloud/policies/engine/serialization/JsonObjectNoNullSerializer.java, external/src/main/resources/application.properties, external/src/test/java/com/redhat/cloud/policies/engine/serialization/TestJsonObjectSerialization.java
Changes serialization to push empty string instead of null field
=> POL-157 Change hooks.outbox serializer 

commons/src/main/resources/ispn-alerting-local.xml, pom.xml
Enables Infinispan statistics in backend and cap some memory limits for RocksDB
=> Modify RocksDB settings

external/pom.xml, external/src/main/resources/application.properties
=> Add support for logging to Sentry

api/src/main/java/com/redhat/cloud/policies/api/model/condition/expression/ExprParser.java, api/src/test/java/com/redhat/cloud/policies/api/model/condition/expression/ExprEvaluationTest.java, api/src/test/java/com/redhat/cloud/policies/api/model/condition/expression/ExprValueTest.java, api/src/test/java/org/hawkular/alerts/api/EventConditionTest.java
This makes the parsing case-insensitive.
=> POL-208 Parser uses lowercase for all values and keys

external/src/main/java/com/redhat/cloud/policies/engine/handlers/AlertsHandler.java
=> Fix a small typo

engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java, engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImplTest.java, engine/src/test/java/org/hawkular/alerts/engine/impl/ispn/IspnDefinitionsServiceImplTest.java
=> POL-293 Provide the real total count to the caller.

external/src/main/java/com/redhat/cloud/policies/engine/handlers/AlertsHandler.java
=> Fix some typos.

external/src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java, external/src/main/resources/application.properties, external/src/test/java/com/redhat/cloud/policies/engine/process/ReceiverTest.java
If the payload says it is a delete event, then skip it.
=> POL-307 Switch to 'platform.inventory.events' topic

pom.xml
=> Allow deployment of engine and its modules to local filerepo

external/src/main/java/com/redhat/cloud/policies/engine/actions/plugins/EmailActionPluginListener.java
=> Remove null or empty tag values from tags that are sent as email

api/src/main/java/com/redhat/cloud/policies/api/model/condition/expression/ExprParser.java, api/src/test/java/com/redhat/cloud/policies/api/model/condition/expression/ExprValidationTest.java, api/src/test/java/com/redhat/cloud/policies/api/model/condition/expression/ExprValueTest.java
Since they can return Collection<String> which is not often what we want.
=> POL-365 POL-366 POL-367 POL-368 Fix the tags odd behavior

api/src/test/java/org/hawkular/alerts/api/EventConditionMsgTest.java, external/src/main/java/com/redhat/cloud/policies/engine/actions/plugins/EmailActionPluginListener.java, external/src/main/java/com/redhat/cloud/policies/engine/actions/plugins/NotificationActionPluginListener.java, external/src/main/resources/alerts.adoc, external/src/main/resources/avro/action.avsc, external/src/test/groovy/org/hawkular/alerts/rest/ActionsITest.groovy, external/src/test/groovy/org/hawkular/alerts/rest/TriggersITest.groovy, external/src/test/java/com/redhat/cloud/policies/engine/process/ReceiverTest.java, external/src/test/resources/import/alerts-data.json, external/src/test/resources/import/groups-data.json
- Adds the params required by the Policies template (on notification)
=> Replaces Webhook plugin with Notification.

external/src/main/java/com/redhat/cloud/policies/engine/actions/plugins/NotificationActionPluginListener.java
After https://github.com/RedHatInsights/notifications-backend/pull/153 is merged
=> NOTIF-163 Rename the bundle

external/pom.xml, external/src/main/docker/Dockerfile.jvm, external/src/main/java/com/redhat/cloud/policies/engine/handlers/ActionsHandler.java, external/src/main/java/com/redhat/cloud/policies/engine/handlers/AlertsHandler.java, external/src/main/java/com/redhat/cloud/policies/engine/handlers/EventsHandler.java, external/src/main/java/com/redhat/cloud/policies/engine/handlers/ImportHandler.java, external/src/main/java/com/redhat/cloud/policies/engine/handlers/TriggersHandler.java, external/src/main/resources/application.properties, external/src/test/java/com/redhat/cloud/policies/engine/process/ReactiveMessagingLifecycleManager.java, external/src/test/java/com/redhat/cloud/policies/engine/process/ReceiverTest.java, pom.xml
I'm still fixing tests, they should fail with the first commit. I want to compare the failures with what I'm seeing locally.
=> Bump Quarkus to 1.13.6.Final

engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java, external/src/main/java/com/redhat/cloud/policies/engine/AlertStarter.java, external/src/main/java/org/hawkular/alerts/AlertsStandalone.java
This could be the solution to the prod config loading issue.
I was able to reproduce the issue locally. It only happens when the app is started with a `java -jar` command.
With the changes from this PR, I was no longer able to reproduce it.
=> Fix config loading race condition

external/src/main/java/com/redhat/cloud/policies/engine/actions/plugins/NotificationActionPluginListener.java, external/src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java, external/src/test/java/com/redhat/cloud/policies/engine/TestLifecycleManager.java, external/src/test/java/com/redhat/cloud/policies/engine/process/ReceiverTest.java
Same as https://github.com/RedHatInsights/notifications-gw/pull/103.
=> NOTIF-309 Send rh-message-id Kafka header

external/src/main/resources/application.properties
Same as https://github.com/RedHatInsights/policies-ui-backend/pull/265.
=> Disable Jaeger

.rhcicd/clowdapp.yaml, .rhcicd/pr_check.sh
Depends on [app-interface!28292](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/28292).
=> POL-543 Clowderize pr_check.sh

external/src/main/java/com/redhat/cloud/policies/engine/history/PoliciesHistory.java
I forgot this was still there 😄
=> POL-560 Remove policies history feature flag

external/src/main/docker/Dockerfile-build.jvm
This will be deployed on fedramp-stage to investigate the issue that prevents the pod from starting.
=> Print JVM heap size at startup

external/src/main/docker/Dockerfile-build.jvm, external/src/main/java/com/redhat/cloud/policies/engine/clowder/KafkaSaslInitializer.java
This PR also removes the `-XX:+PrintFlagsFinal` JVM flag that was needed to investigate a fedramp-stage issue.
=> POL-621 Introduce KafkaSaslInitializer

external/src/main/java/com/redhat/cloud/policies/engine/clowder/KafkaSaslInitializer.java
Final version of the Kafka SASL config initialization, probably 😄
=> POL-621 Restore KafkaSaslInitializer

external/src/main/resources/application.properties
This will make the debugging on stage easier.
=> POL-649 Set LightweightEngineImpl log level to DEBUG

external/src/main/java/com/redhat/cloud/policies/engine/LightweightEngineImpl.java
They don't really make sense anymore but I kept the old metrics names to make the monitoring in Prometheus/Grafana easier while we transition from the old engine to the new one.
=> POL-649 Add LightweightEngineImpl metrics

external/src/main/java/com/redhat/cloud/policies/engine/LightweightEngineImpl.java
Before this PR, the new engine sends notifications even if `notifications` hasn't been selected as a policy action in the frontend.
=> POL-649 Check trigger action before sending a notification

pom.xml, src/main/java/com/redhat/cloud/policies/engine/metrics/ProcSelfStatusExporter.java, src/main/java/com/redhat/cloud/policies/engine/process/EventProcessor.java, src/main/java/com/redhat/cloud/policies/engine/process/NotificationSender.java, src/main/java/com/redhat/cloud/policies/engine/process/PayloadParser.java, src/test/java/com/redhat/cloud/policies/engine/process/PayloadParserTest.java
the build takes hours.. I am expecting that there are still some failing tests.
=> Migrate to micrometer metrics

.github/workflows/checkupdate.yml
Same as https://github.com/RedHatInsights/policies-ui-backend/pull/448.
=> Change PR and commit messages of ubi-minimal updates

src/main/java/com/redhat/cloud/policies/engine/clowder/KafkaSaslInitializer.java
Same as https://github.com/RedHatInsights/notifications-backend/pull/1344.
=> RHCLOUD-20150 Connect to managed Kafka using Clowder

pom.xml, src/main/java/com/redhat/cloud/policies/engine/process/Receiver.java
=> Bump Quarkus from 2.12.3.Final to 2.13.3.Final

.rhcicd/clowdapp.yaml, pom.xml, src/main/java/com/redhat/cloud/policies/engine/process/EventProcessor.java, src/main/java/com/redhat/cloud/policies/engine/process/NotificationSender.java, src/main/java/com/redhat/cloud/policies/engine/process/PolicyTriggeredCloudEvent.java, src/test/java/com/redhat/cloud/policies/engine/process/EventProcessorTest.java, src/test/java/com/redhat/cloud/policies/engine/process/NotificationSenderTest.java
- Setting the base env url in clowdapp
- Updating event-schemas version
- Relax validation for description
- Correctly decode /encode the date-time
- policy ids are uuids
=> Fix missing details for cloud events

.github/workflows/checkupdate.yml
Check for package updates for the container image.
=> ci: check package updates

src/main/java/com/redhat/cloud/policies/engine/clowder/KafkaSaslInitializer.java
This should help fix the `policies-engine` deployment in stage.
I made the [same kind of change](https://github.com/RedHatInsights/notifications-backend/pull/2216) in Notifications and now everything works like a charm.
=> Make Kafka config init compatible with MSK

.rhcicd/clowdapp.yaml
=> fix: sentry dsn templated

pom.xml
=> chore(pom): update packages

src/main/resources/application.properties
=> feat: reduce access log

.dockerignore, .rhcicd/build_deploy.sh
=> ci: temp dir for docker

pom.xml
=> chore: update Quarkus platform

src/test/java/com/redhat/cloud/policies/engine/TestLifecycleManager.java
Fixes test runs with testcontainers with podman by specifying the image with repository.
=> fix(tests): use specific postgres container image

.rhcicd/clowdapp.yaml
=> feat(clowder): pull the container image from konflux quay

.github/workflows/checkupdate.yml, src/main/docker/Dockerfile-build.jvm
RHINENG-13893
Please merge only when Konflux supports UBI8 (Monday 28th of Oct).
=> Revert to UBI8 container

.rhcicd/pr_check.sh
closes [RHCLOUD-36026](https://issues.redhat.com/browse/RHCLOUD-36026)
=> use cicd-tools instead of bonfire repo.

src/main/resources/application.properties
=> fix: load Kafka SSL config from clowder

src/main/docker/Dockerfile-build.jvm
After the Kafka OOM is fixed, getting back to the previou-ish values.
RHINENG-15124
=> chore(cleanup): reduce heap

pom.xml
- Bump Policies version to `2.1.1`
=> Bump Version 2.1.1
